//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IvNetSwitcher.UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://google.com")]
        public string HostToPing {
            get {
                return ((string)(this["HostToPing"]));
            }
            set {
                this["HostToPing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int DelayInSec {
            get {
                return ((int)(this["DelayInSec"]));
            }
            set {
                this["DelayInSec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("730DE481-2077-4D59-AF65-543669121202")]
        public string EncSalt {
            get {
                return ((string)(this["EncSalt"]));
            }
            set {
                this["EncSalt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          <ArrayOfProfileDto xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
            <ProfileDto>
              <Id>1</Id>
              <Name>name</Name>
              <User>user</User>
              <Password>Y7kMhDfy6OBXqP2BhzkQiIobGxyYdNtZVxCv3z3sZNiER/SAvYifycBy6yj5rUMrBZ3dwe9YarugZNVWgintZeRK8o64C9ggi/8rLEih/kHxklsOV4VLm1ranm9Z9DsJ</Password>
              <Domain>domain</Domain>
              <Comment>comment</Comment>
              <Active>false</Active>
            </ProfileDto>
          </ArrayOfProfileDto>
        ")]
        public string Profiles {
            get {
                return ((string)(this["Profiles"]));
            }
            set {
                this["Profiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Retry {
            get {
                return ((int)(this["Retry"]));
            }
            set {
                this["Retry"] = value;
            }
        }
    }
}
